name: learners_exam_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
    


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  lottie: ^2.3.2
  flutter_svg: ^2.0.5
  google_fonts: ^5.0.0
  url_launcher: ^6.1.11
  device_preview: ^1.1.0
  http: ^1.0.0
  google_mobile_ads: ^4.0.0
  provider: ^6.1.1
  connectivity_plus: ^5.0.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0

flutter_icons:
  android: "logo"
  ios: true
  image_path: "images/main_app_images/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - json_database/Road_signs/road_sign_categories.json
    - json_database/Road_signs/warning_signs.json
    - json_database/Road_signs/regulatory_signs.json
    - json_database/Road_signs/guidance_signs.json
    - json_database/Road_signs/various_signs.json
    - json_database/Road_signs/roadmark_signs.json
    - json_database/Road_signs/other_signs.json
    - json_database/Road_signs/vehicle_control_signs.json
    - json_database/Road_signs/traffic_light_signs.json
    - json_database/mcqAll.json

    - images/main_app_images/beelogo.png
    - images/main_app_images/json/firstscreen.json
    - images/png/arrowright.png
    - images/png/bridge.png
    - images/png/correctmark.png
    - images/png/facebook.png
    - images/png/menu.png
    - images/png/modelpapers.png
    - images/png/pen.png 
    - images/png/supportus.png
    - images/png/wrong.png
    - images/Categories/road_sign_categories/1.png
    - images/Categories/road_sign_categories/2.png
    - images/Categories/road_sign_categories/3.png
    - images/Categories/road_sign_categories/4.png
    - images/Categories/road_sign_categories/5.png
    - images/Categories/road_sign_categories/6.png
    - images/Categories/road_sign_categories/7.png
    - images/Categories/road_sign_categories/8.png

    - images/png/warning_signs/dws1.png
    - images/png/warning_signs/dws2.png
    - images/png/warning_signs/dws3.png
    - images/png/warning_signs/dws4.png
    - images/png/warning_signs/dws5.png
    - images/png/warning_signs/dws6.png
    - images/png/warning_signs/dws7.png
    - images/png/warning_signs/dws8.png
    - images/png/warning_signs/dws9.png
    - images/png/warning_signs/dws10.png
    - images/png/warning_signs/dws11.png
    - images/png/warning_signs/dws12.png
    - images/png/warning_signs/dws13.png
    - images/png/warning_signs/dws14.png
    - images/png/warning_signs/dws15.png
    - images/png/warning_signs/dws16.png
    - images/png/warning_signs/dws17.png
    - images/png/warning_signs/dws18.png
    - images/png/warning_signs/dws19.png
    - images/png/warning_signs/dws20.png
    - images/png/warning_signs/dws21.png
    - images/png/warning_signs/dws22.png
    - images/png/warning_signs/dws23.png
    - images/png/warning_signs/dws24.png
    - images/png/warning_signs/dws25.png
    - images/png/warning_signs/dws26.png
    - images/png/warning_signs/dws27.png
    - images/png/warning_signs/dws28.png
    - images/png/warning_signs/dws29.png
    - images/png/warning_signs/dws30.png
    - images/png/warning_signs/dws31.png
    - images/png/warning_signs/dws32.png
    - images/png/warning_signs/dws33.png
    - images/png/warning_signs/dws34.png
    - images/png/warning_signs/dws35.png
    - images/png/warning_signs/dws36.png
    - images/png/warning_signs/dws37.png
    - images/png/warning_signs/dws38.png
    - images/png/warning_signs/dws39.png
    - images/png/warning_signs/dws40.png
    - images/png/warning_signs/dws41.png
    - images/png/warning_signs/dws42.png
    - images/png/warning_signs/dws43.png
    - images/png/warning_signs/dws44.png
    - images/png/warning_signs/dws45.png
    - images/png/warning_signs/dws46.png
    - images/png/warning_signs/dws47.png
    - images/png/warning_signs/dws48.png
    - images/png/warning_signs/dws49.png
    - images/png/warning_signs/dws50.png
    - images/png/warning_signs/dws51.png
    - images/png/warning_signs/apd1.png
    - images/png/warning_signs/apd2.png
    - images/png/warning_signs/apd3.png
    - images/png/warning_signs/apd4.png

    - images/png/regulatory_signs/phs1.png
    - images/png/regulatory_signs/phs2.png
    - images/png/regulatory_signs/phs3.png
    - images/png/regulatory_signs/phs4.png
    - images/png/regulatory_signs/phs5.png
    - images/png/regulatory_signs/phs6.png
    - images/png/regulatory_signs/phs7.png
    - images/png/regulatory_signs/phs8.png
    - images/png/regulatory_signs/phs9.png
    - images/png/regulatory_signs/phs10.png
    - images/png/regulatory_signs/phs11.png
    - images/png/regulatory_signs/phs12.png
    - images/png/regulatory_signs/phs13.png
    - images/png/regulatory_signs/phs14.png
    - images/png/regulatory_signs/phs15.png
    - images/png/regulatory_signs/phs16.png
    - images/png/regulatory_signs/phs17.png
    - images/png/regulatory_signs/phs18.png
    - images/png/regulatory_signs/phs19.png
    - images/png/regulatory_signs/phs20.png
    - images/png/regulatory_signs/phs21.png
    - images/png/regulatory_signs/phs22.png
    - images/png/regulatory_signs/phs23.png
    - images/png/regulatory_signs/phs24.png
    - images/png/regulatory_signs/phs25.png
    - images/png/regulatory_signs/phs26.png
    - images/png/regulatory_signs/phs27.png
    - images/png/regulatory_signs/phs28.png
    - images/png/regulatory_signs/phs29.png
    - images/png/regulatory_signs/phs30.png
    - images/png/regulatory_signs/phs31.png
    - images/png/regulatory_signs/phs32.png
    - images/png/regulatory_signs/phs33.png
    - images/png/regulatory_signs/phs34.png
    - images/png/regulatory_signs/phs35.png
    - images/png/regulatory_signs/phs36.png
    - images/png/regulatory_signs/phs37.png
    - images/png/regulatory_signs/phs38.png
    - images/png/regulatory_signs/phs39.png
    - images/png/regulatory_signs/phs40.png
    - images/png/regulatory_signs/phs41.png
    - images/png/regulatory_signs/phs42.png
    - images/png/regulatory_signs/phs43.png
    - images/png/regulatory_signs/phs44.png
    - images/png/regulatory_signs/phs45.png
    - images/png/regulatory_signs/phs46.png
    - images/png/regulatory_signs/phs47.png
    - images/png/regulatory_signs/phs48.png
    - images/png/regulatory_signs/phs49.png
    - images/png/regulatory_signs/phs50.png
    - images/png/regulatory_signs/phs51.png
    - images/png/regulatory_signs/phs52.png
    - images/png/regulatory_signs/phs53.png
    - images/png/regulatory_signs/phs54.png
    - images/png/regulatory_signs/phs55.png
    - images/png/regulatory_signs/phs56.png
    - images/png/regulatory_signs/phs57.png
    - images/png/regulatory_signs/phs58.png
    - images/png/regulatory_signs/phs59.png
    - images/png/regulatory_signs/phs60.png
    - images/png/regulatory_signs/phs61.png
    - images/png/regulatory_signs/phs62.png
    - images/png/regulatory_signs/phs63.png
    - images/png/regulatory_signs/phs64.png
    - images/png/regulatory_signs/phs65.png

    - images/png/guidance_signs/is(nh)1.jpg
    - images/png/guidance_signs/is(nh)2.jpg
    - images/png/guidance_signs/is(nh)3.jpg
    - images/png/guidance_signs/is(nh)4.jpg
    - images/png/guidance_signs/is(nh)5.jpg
    - images/png/guidance_signs/is(nh)6.jpg
    - images/png/guidance_signs/is(nh)7.jpg
    - images/png/guidance_signs/is(nh)8.jpg
    - images/png/guidance_signs/is(nh)9.jpg
    - images/png/guidance_signs/is(nh)10.jpg
    - images/png/guidance_signs/is(nh)11.jpg
    - images/png/guidance_signs/is(pr)1.jpg
    - images/png/guidance_signs/is(pr)2.jpg
    - images/png/guidance_signs/is(pr)3.jpg
    - images/png/guidance_signs/is(pr)4.jpg
    - images/png/guidance_signs/is(pr)5.jpg
    - images/png/guidance_signs/is(ex)1.jpg
    - images/png/guidance_signs/is(ex)2.jpg
    - images/png/guidance_signs/is(ex)3.jpg
    - images/png/guidance_signs/is(ex)4.jpg
    - images/png/guidance_signs/is(ex)5.jpg
    - images/png/guidance_signs/is(ex)6.jpg
    - images/png/guidance_signs/is(ex)7.jpg
    - images/png/guidance_signs/ods1.jpg
    - images/png/guidance_signs/ods2.jpg
    - images/png/guidance_signs/ods3.jpg
    - images/png/guidance_signs/ods4.jpg
    - images/png/guidance_signs/ods5.jpg
    - images/png/guidance_signs/ods6.jpg
    - images/png/guidance_signs/ods7.jpg
    - images/png/guidance_signs/ods8.jpg
    - images/png/guidance_signs/ods9.jpg
    - images/png/guidance_signs/ods10.jpg
    - images/png/guidance_signs/ods11.jpg
    - images/png/guidance_signs/ods12.jpg
    - images/png/guidance_signs/ods13.jpg
    - images/png/guidance_signs/ods14.jpg
    - images/png/guidance_signs/ods15.jpg
    - images/png/guidance_signs/ods16.jpg
    - images/png/guidance_signs/ods17.jpg
    - images/png/guidance_signs/ods18.jpg
    - images/png/guidance_signs/ods19.jpg
    - images/png/guidance_signs/ods20.jpg
    - images/png/guidance_signs/ods21.jpg
    - images/png/guidance_signs/ods22.jpg
    - images/png/guidance_signs/ods23.jpg
    - images/png/guidance_signs/ods24.jpg
    - images/png/guidance_signs/ods25.jpg

    - images/png/guidance_signs/rns1.jpg
    - images/png/guidance_signs/rns2.jpg
    - images/png/guidance_signs/rns3.jpg
    - images/png/guidance_signs/rns4.jpg
    - images/png/guidance_signs/api1.jpg
    - images/png/guidance_signs/api2.jpg
    - images/png/guidance_signs/api3.jpg

    - images/png/various_signs/ms1.jpg
    - images/png/various_signs/ms2.jpg
    - images/png/various_signs/ms3.jpg
    - images/png/various_signs/ms4.jpg
    - images/png/various_signs/ms5.jpg
    - images/png/various_signs/ms6.jpg
    - images/png/various_signs/ms7.jpg
    - images/png/various_signs/ms8.jpg
    - images/png/various_signs/ms9.jpg
    - images/png/various_signs/ms10.jpg
    - images/png/various_signs/ms11.jpg
    - images/png/various_signs/ms12.jpg
    - images/png/various_signs/ms13.jpg
    - images/png/various_signs/ms14.jpg
    - images/png/various_signs/ms15.jpg
    - images/png/various_signs/ms16.jpg
    - images/png/various_signs/ms17.jpg
    - images/png/various_signs/ms18.jpg
    - images/png/various_signs/ms19.jpg
    - images/png/various_signs/ms20.jpg

    - images/png/roadmark_signs/rm1.jpg
    - images/png/roadmark_signs/rm2.jpg
    - images/png/roadmark_signs/rm3.jpg
    - images/png/roadmark_signs/rm4.jpg
    - images/png/roadmark_signs/rm5.jpg
    - images/png/roadmark_signs/rm6.jpg
    - images/png/roadmark_signs/rm7.jpg
    - images/png/roadmark_signs/rm8.jpg
    - images/png/roadmark_signs/rm9.jpg
    - images/png/roadmark_signs/rm10.jpg
    - images/png/roadmark_signs/rm11.jpg
    - images/png/roadmark_signs/rm12.jpg
    - images/png/roadmark_signs/rm13.jpg
    - images/png/roadmark_signs/rm14.jpg
    - images/png/roadmark_signs/rm15.jpg
    - images/png/roadmark_signs/rm16.jpg
    - images/png/roadmark_signs/rm17.jpg
    - images/png/roadmark_signs/rm18.jpg
    - images/png/roadmark_signs/rm19.jpg
    - images/png/roadmark_signs/rm20.jpg
    - images/png/roadmark_signs/rm21.jpg
    - images/png/roadmark_signs/rm22.jpg
    - images/png/roadmark_signs/rm23.jpg
    - images/png/roadmark_signs/rm24.jpg
    - images/png/roadmark_signs/rm25.jpg
    - images/png/roadmark_signs/rm26.jpg
    - images/png/roadmark_signs/rm27.jpg
    - images/png/roadmark_signs/rm28.jpg
    - images/png/roadmark_signs/rm29.jpg
    - images/png/roadmark_signs/rm30.jpg
    - images/png/roadmark_signs/rm31.jpg
    - images/png/roadmark_signs/rm32.jpg
    - images/png/roadmark_signs/rm33.jpg
    - images/png/roadmark_signs/rm34.jpg
    - images/png/roadmark_signs/rm35.jpg
    - images/png/roadmark_signs/rm36.jpg
    - images/png/roadmark_signs/rm37.jpg
    - images/png/roadmark_signs/rm38.jpg
    - images/png/roadmark_signs/rm39.jpg
    - images/png/roadmark_signs/rm40.jpg
    - images/png/roadmark_signs/rm41.jpg
    - images/png/roadmark_signs/rm42.jpg
    - images/png/roadmark_signs/rm43.jpg
    - images/png/roadmark_signs/rm44.jpg
    - images/png/roadmark_signs/rm45.jpg
    - images/png/roadmark_signs/rm46.jpg
    - images/png/roadmark_signs/rm47.jpg
    - images/png/roadmark_signs/rm48.jpg
    - images/png/roadmark_signs/rm49.jpg
    - images/png/roadmark_signs/rm50.jpg
    - images/png/roadmark_signs/rm51.jpg
    - images/png/roadmark_signs/rm52.jpg
    - images/png/roadmark_signs/rm53.jpg
    - images/png/roadmark_signs/rm54.jpg

    - images/png/other_signs/hwp1.png
    - images/png/other_signs/hwp2.png
    - images/png/other_signs/hwp3.png
    - images/png/other_signs/hwp4.png
    - images/png/other_signs/hwp5.png
    - images/png/other_signs/hwp6.png
    - images/png/other_signs/hwp7.png
    - images/png/other_signs/hwp8.png
    - images/png/other_signs/hwp9.png

    - images/png/vehicle_control_signs/hsp1.png
    - images/png/vehicle_control_signs/hsp2.png
    - images/png/vehicle_control_signs/hsp3.png
    - images/png/vehicle_control_signs/hsp4.png
    - images/png/vehicle_control_signs/hsp5.png
    - images/png/vehicle_control_signs/hsp6.png
    - images/png/vehicle_control_signs/sdr1.jpg
    - images/png/vehicle_control_signs/sdr2.jpg
    - images/png/vehicle_control_signs/sdr3.jpg
    - images/png/vehicle_control_signs/dis1.jpg
    - images/png/vehicle_control_signs/dis2.jpg
    - images/png/vehicle_control_signs/dis3.jpg

    - images/png/traffic_light_signs/aps1.jpg
    - images/png/traffic_light_signs/aps2.jpg
    - images/png/traffic_light_signs/aps3.jpg
    - images/png/traffic_light_signs/aps4.jpg
    - images/png/traffic_light_signs/aps5.jpg
    - images/png/traffic_light_signs/gap1.jpg
    - images/png/traffic_light_signs/gap2.jpg
    - images/png/traffic_light_signs/gap3.jpg
    - images/png/traffic_light_signs/gap4.jpg
    - images/png/traffic_light_signs/gap5.jpg
    - images/png/traffic_light_signs/gap6.jpg
    - images/png/traffic_light_signs/gap7.jpg
    - images/png/traffic_light_signs/gap8.jpg
    - images/png/traffic_light_signs/gap9.jpg
    - images/png/traffic_light_signs/gap10.jpg
    - images/png/traffic_light_signs/gap11.jpg
    - images/png/traffic_light_signs/gap12.jpg
    - images/png/traffic_light_signs/lsp1.jpg
    - images/png/traffic_light_signs/lsp2.jpg
    - images/png/traffic_light_signs/lsp3.jpg
    - images/png/traffic_light_signs/oms1.png
    - images/png/traffic_light_signs/oms2.png
    - images/png/traffic_light_signs/pdv1.jpg
    - images/png/traffic_light_signs/pdv2.jpg
    - images/png/traffic_light_signs/pdv3.jpg
    - images/png/traffic_light_signs/pdv4.jpg
    - images/png/traffic_light_signs/pdv5.jpg
    - images/png/traffic_light_signs/pdv6.jpg
    - images/png/traffic_light_signs/pdv7.jpg
    - images/png/traffic_light_signs/pdv8.jpg
    - images/png/traffic_light_signs/pdv9.jpg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Raleway
      fonts:
        - asset: images/font/raleway.ttf
  #       - asset: images/font/raleway.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
